### ISSUE TITLE
About the datasets

### ISSUE THREAD

**Issue by wuxiaofenghehe** [zhangyin1996/ISP-Teacher#3]
Hi, I want to reproduce your code on my computer, can you provide your data set, or how it is divided.

**Comment by zhangyin1996** [comment]
@wuxiaofenghehe 
Thank you for your interest in our work!
Due to copyright, I cannot freely provide you the dataset. You can download it from the official website.
BDD100k: https://www.vis.xyz/bdd100k/
SHIFT: https://www.vis.xyz/shift/
And for labels, you can refer to README.md ''2. Datasets'' to obtain.

 If you think our work is helpful to you, please give our repository a star~
